[package]
name = "toto_semantic"
version.workspace = true
edition.workspace = true

[dependencies]
url.workspace = true
petgraph.workspace = true
ariadne.workspace = true
toto_ast = { path = "../toto_ast" }
toto_tosca = { path = "../toto_tosca" }
toto_parser = { path = "../toto_parser" }
