[package]
name = "toto_ir"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more.workspace = true
toto_ast = { path = "../toto_ast" }
toto_yaml = { path = "../toto_yaml" }
toto_parser = { path = "../toto_parser" }
toto_tosca = { path = "../toto_tosca" }
