[package]
name = "toto_ast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = { version = "0.6.4", features = ["all", "serde"] }
toto_tosca = { path = "../toto_tosca" }
